name: ai_buddy
description: A scalable Flutter app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  flutter_bloc: ^8.1.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  go_router: ^11.1.3
  package_info_plus: ^4.2.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0

  # iOS
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  fluttericon: ^2.0.0
  lottie: ^3.0.0
  flutter_chat_ui: ^1.6.12
  uuid: ^4.3.3
  flutter_chat_types: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
